extends:
  - "airbnb-base"
env:
  node: true
  browser: true
parser: "babel-eslint"
rules:
  no-console: 0
  no-use-before-define: 0
  no-param-reassign: 0
  no-unused-vars: 0
  no-alert: 0
  linebreak-style: ["error", "windows"]